[project]
name = "yolo-conversion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coremltools>=9.0",
    "huggingface-hub>=1.2.3",
    "ultralytics>=8.3.239",
]
